### ISSUE TITLE
Fix ruby 2.7 keyword argument warnings

### ISSUE THREAD

**Issue by rkrage** [rkrage/pg_party#49]
The 2.7 builds have a ton of deprecation warnings like:

```
Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

This is due to the work to separate positional and keyword args: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

**Comment by AlexMooney** [comment]
I've made a PR to fix up the warnings that come out of pg_party code.  The tests are still noisy because they hit some Rails 5.* apps.

Thanks for making this gem!  It was really useful for us to be able to build up big tables in a Rails app and then DROP the individual partitions instead of doing DELETE WHERE.

**Comment by rkrage** [comment]
I _think_ this one can be closed. Not seeing any keyword arg warnings on the latest version of Rails
